name: Deploy Backend Minimal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run backend container with minimal env variables
        run: |
          docker run -d \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e MONGO_DB_NAME="${{ secrets.MONGO_DB_NAME }}" \
            -e PORT="${{ secrets.PORT }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e JWT_EXPIRATION="${{ secrets.JWT_EXPIRATION }}" \
            -e JWT_ALGORITHM="${{ secrets.JWT_ALGORITHM }}" \
            -p 4000:4000 \
            salvadorvgac04/krs-v1-backend:latest
