name: Build and Push Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Backend
      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend   # Carpeta donde está el Dockerfile del backend
          push: true
          tags: |
            salvadorvgac04/krs-v1-backend:latest
            salvadorvgac04/krs-v1-backend:${{ github.sha }}

      # 4. Frontend
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./FrondEnd/my-krs  # Carpeta donde está el Dockerfile del frontend
          push: true
          tags: |
            salvadorvgac04/krs-v1-frontend:latest
            salvadorvgac04/krs-v1-frontend:${{ github.sha }}
